name: '🌓  Make a release for us'
on:
  workflow_dispatch:
    inputs:
      versionToRelease:
        description: 'Version (1.X.X, not v1.X.X)'
        required: true

jobs:
  MakeRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Node.js 17.x
        uses: actions/setup-node@v2
        with:
          node-version: 17
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Build Typescript
        run: yarn build

      - name: Check version
        run: node packages/moonlight-release/dist/checkVersion.js

      - name: Le chapon
        run: node packages/moonlight-release/dist/index.js
